### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by StanislavLohtin** [friendlyantz/who_is_america#29]
Add search / filter. add Party widget

**Comment by friendlyantz** [comment]
- [ ] content from backend logic

**Comment by friendlyantz** [comment]
close this one? @stanislav-lohtin @StanislavLohtin

**Comment by StanislavLohtin** [comment]
nah. ill add description

**Comment by friendlyantz** [comment]
complete. pull request for your kind review @StanislavLohtin
